---
apiVersion: v1
kind: Service
metadata:
  name: petclinic
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: petclinic

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: petclinic
  labels:
    app: petclinic
spec:
  replicas: 1
  selector:
    matchLabels:
      app: petclinic
  template:
    metadata:
      labels:
        app: petclinic
    spec:
      imagePullSecrets:
        - name: ghcr-login-secret
      containers:
        - name: workload
          image: ghcr.io/alexanderlindahl/platform-school-petclinic-lindahl:latest
          imagePullPolicy: Always
      volumes:
        - name: binding
          projected:
            sources:
              - secret:
                  name: demo-db
